package setup

import (
	"os"
	"path/filepath"
)

// opencodePluginTemplate is the tt-bridge.ts content generated by SetupOpencode.
// Uses ES5 string concatenation to avoid backtick conflicts with Go raw strings.
var opencodePluginTemplate = `"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var child_process_1 = require("child_process");
var seen = new Set();
var pendingSubTokens = {};
function resolveProject(directory) {
    try {
        return child_process_1.execSync("git -C " + JSON.stringify(directory) + " rev-parse --show-toplevel", { encoding: "utf-8" }).trim();
    }
    catch (_a) {
        return directory;
    }
}
function default_1(info) {
    return {
        name: "tt-bridge",
        onEvent: function (event) {
            var _a, _b, _c, _d, _e, _f;
            if (event.type !== "message.updated") return;
            var msg = event.message;
            if (!msg) return;
            var sessionID = (_a = info.sessionID) !== null && _a !== void 0 ? _a : "";
            var directory = (_b = info.directory) !== null && _b !== void 0 ? _b : process.cwd();
            var role = msg.role;
            var agent = (_c = info.agent) !== null && _c !== void 0 ? _c : "";
            if (role === "user" && ((_d = event.time) === null || _d === void 0 ? void 0 : _d.created)) {
                var model = ((_e = info.model) === null || _e === void 0 ? void 0 : _e.modelID) !== null && ((_f = info.model) === null || _f === void 0 ? void 0 : _f.modelID) !== void 0 ? (_e = info.model) === null || _e === void 0 ? void 0 : _e.modelID : "";
                var project = resolveProject(directory);
                try {
                    child_process_1.execSync("tt record prompt --tool opencode --session " + JSON.stringify(sessionID) + " --project " + JSON.stringify(project) + " --model " + JSON.stringify(model), { stdio: "ignore" });
                }
                catch (_g) {}
                return;
            }
            if (role === "assistant") {
                var modelID = info.model && info.model.modelID;
                var tokens = info.tokens;
                if (!modelID || !tokens) return;
                if (agent) {
                    if (!pendingSubTokens[sessionID]) pendingSubTokens[sessionID] = {};
                    pendingSubTokens[sessionID][msg.id] = {
                        model: modelID,
                        agent: agent,
                        input_tokens: tokens.input || 0,
                        output_tokens: tokens.output || 0,
                        cache_read_tokens: tokens.cacheRead || 0,
                        cache_creation_tokens: tokens.cacheCreation || 0,
                        reasoning_tokens: tokens.reasoning || 0,
                    };
                    return;
                }
                if (!((_g = event.time) === null || _g === void 0 ? void 0 : _g.completed) && !msg.finish) return;
                var dedupKey = msg.id + "-" + tokens.input + "-" + tokens.output + "-" + (tokens.cacheRead || 0);
                if (seen.has(dedupKey)) return;
                seen.add(dedupKey);
                var tokensJSON = JSON.stringify({
                    input_tokens: tokens.input || 0,
                    output_tokens: tokens.output || 0,
                    cache_read_tokens: tokens.cacheRead || 0,
                    cache_creation_tokens: tokens.cacheCreation || 0,
                    reasoning_tokens: tokens.reasoning || 0,
                });
                var cmd = "tt record response --tool opencode --session " + JSON.stringify(sessionID) + " --model " + JSON.stringify(modelID) + " --tokens " + JSON.stringify(tokensJSON);
                var subs = pendingSubTokens[sessionID];
                if (subs && Object.keys(subs).length > 0) {
                    var subArr = Object.values(subs).flat();
                    cmd += " --subagent-tokens " + JSON.stringify(JSON.stringify(subArr));
                    delete pendingSubTokens[sessionID];
                }
                try {
                    child_process_1.execSync(cmd, { stdio: "ignore" });
                }
                catch (_h) {}
            }
        },
    };
}
exports.default = default_1;
`

// SetupOpencode generates the tt-bridge.ts plugin file for opencode.
// It is idempotent: if the file already exists, it is not overwritten.
func SetupOpencode() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	pluginDir := filepath.Join(home, ".config", "opencode", "plugins")
	pluginPath := filepath.Join(pluginDir, "tt-bridge.ts")

	// Idempotent: skip if already present
	if _, err := os.Stat(pluginPath); err == nil {
		return nil
	}

	// Create parent directories
	if err := os.MkdirAll(pluginDir, 0o700); err != nil {
		return err
	}

	return os.WriteFile(pluginPath, []byte(opencodePluginTemplate), 0o600)
}

// IsOpenCodeActive checks if the ~/.config/opencode directory exists.
func IsOpenCodeActive() bool {
	return isDirActive(filepath.Join(".config", "opencode"))
}
